spring.application.name=SprinAICode
spring.ai.openai.api-key=${openAiKey}


spring.ai.ollama.chat.model=smollm2
spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.embedding.model=nomic-embed-text